# Generated by Django 4.1.3 on 2022-12-24 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Umedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('detalles', models.CharField(max_length=200)),
                ('cantidad', models.IntegerField(default=0)),
                ('umedida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.umedida')),
            ],
        ),
    ]
