# Generated by Django 4.1.3 on 2022-12-28 17:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaMov', models.DateField(default=django.utils.timezone.now)),
                ('tipoMov', models.CharField(max_length=50)),
                ('detallesMov', models.CharField(max_length=300)),
                ('cantidadMov', models.IntegerField()),
                ('artId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_inventario.articulos')),
            ],
        ),
    ]
