# Generated by Django 4.1.3 on 2022-12-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0002_movimientos1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos1',
            name='tipoMov',
            field=models.CharField(choices=[('ingreso', 'ingreso'), ('egreso', 'egreso')], max_length=50),
        ),
    ]
